name: Metrics
on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Generate README.md
      uses: teoxoy/profile-readme-stats@v2
      with:
        token: ${{ secrets.METRICS_TOKEN }}
    - name: Setup git config
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
    - name: Commit README.md
      run: |
        git add .
        git commit -m "Update README.md"
        git push origin master
    - name: Update Last.fm Charts
      uses: dxnter/lastfm-readme@v1
      with:
        LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
        LASTFM_USER: lyqst
